### PR TITLE
Fix markup on z3c input fields

### PR DESCRIPTION
**Pull request by pysailor**
get rid of unnecessary and unwanted `<div>` with class z3cFieldContainer around some input widgets

### CODE REVIEW

**Comment by wichert** [comment]
Doesn't this break all dependency-support?

**Comment by pysailor** [comment]
Well, what actually depends on this? I saw that this `<div>` was not even used in all inputs widgets.
Following the discussion with @cornae in euphorie/osha.oira#50, I had overwritten the 3 inputs that are used by the new Euphorie interface in osha.oira. Since the new UI will become part of Euphorie core, I figured I might as well fix the problem at its root (NuPlone), rather than customising the 3 templates in Euphorie.
But, I must confess, I have no idea what other projects are still using NuPlone, so yes, a new release might break backwards compatibility.

**Comment by wichert** [comment]
At least the risk and new survey forms in Euphorie make very heavy use of dependencies. If you want to remove dependency support like this I think we need to go through a couple of steps:

* [ ] Audit Euphorie, tno.euphorie and osha.oira to make sure they do not use dependencies anywhere (a grep should suffice)
* [ ] Remove all the dependency-handling logic from NuPlone.
* [ ] Do a major version bump.

Without the last step we would have the awkward situation where there is a lot of dependency-related code but no UI to take advantage of it.

**Comment by pysailor** [comment]
It took me a while to understand what you mean, but of course, you're right: My change would break widgets using `plonetheme.nuplone.z3cform.directives.depends` (at least those which don't already have a tag surrounding the whole widget markup like radio_input). And indeed, the backend for Euphorie uses this directive a lot, and I would not want to remove that :)

The problem I'm trying to fix arises from functional templates in the client (for changing password or email address) that use z3c.form and thereby the NuPlone templates. I could rewrite those to normal browser views, but they're good the way they are, except for the unwanted `<div>` in the widget markup.

I pushed a new version of how I'd fix this: Use a `<span>` instead of a `<div>`, and only show it if there's actually a dependency. In the client, this will never be the case, since we have the beauty of `pat-depends` from patternslib at our disposal. And in the backend, existing dependencies still work.

**Comment by wichert** [comment]
Thanks, that looks a lot better!

**Comment by pysailor** [comment]
Great, can this PR be merged?

**Pull request merged**
